server:
    port: 8080

# ===============================
# = JPA / HIBERNATE
# ===============================

spring:
 datasource:
  testWhileIdle: false
  validationQuery: SELECT 1
  max-active: 50
  max-idle: 5
  min-idle: 5
  initial-size: 10
 http:
  encoding:
   charset: UTF-8
 jpa:
  show-sql: false
  hibernate:
   naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
   ddl-auto: update



# ###########################################################
# "create"      - to build a new database on each run;
# "update"      - to modify an existing database;
# "create-drop" - "create" but also drops tables when Hibernate closes;
# "validate"    - makes no changes to the database
#  jpa:
#      hibernate:
#              ddl-auto: create
# ###########################################################
#none, validate, update, create, create-drop



---

# ###########################################################
# MySQL Database
# ###########################################################


spring:
 profiles: tomMySQL
 datasource:
  platform: sql
  driver-class-name: com.mysql.jdbc.Driver
  url: jdbc:mysql://localhost:3306/testdb?verifyServerCertificate=false&useSSL=false&requireSSL=false
  username: root
  password: root
  validation-query: select 1
 jpa:
  database: MYSQL
  show-sql: false
  properties:
   hibernate:
    dialect: org.hibernate.dialect.MySQL5Dialect
    ddl-auto: create


logging:
 file: /Captains.log

---


# ###########################################################
# H2 Database
# ###########################################################

spring:
     profiles: h2InMemoryDatabase
     h2:
      console:
       enabled: true
       path: /h2-console
     jpa:
      database-platform: H2
      hibernate:
       ddl-auto: create-drop
       naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
      database: h2
      show-sql: false
     datasource:
       driver-class-name: org.h2.Driver
       url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
       username: root
       password: root
       validation-query: select 1
     jooq:
       sql-dialect: org.hibernate.dialect.H2Dialect


---



