server:
    port: 8080



# ###########################################################
# "create"      - to build a new database on each run;
# "update"      - to modify an existing database;
# "create-drop" - "create" but also drops tables when Hibernate closes;
# "validate"    - makes no changes to the database
#  jpa:
#      hibernate:
#              ddl-auto: create
# ###########################################################
#none, validate, update, create, create-drop


#
---

# ###########################################################
# MySQL Database
# ###########################################################

#spring:
#  profiles: tomMySQL
#  jpa:
#   database: MYSQL


#spring:
#  profiles: tomMySQL
#  jpa:
#   hibernate:
#    ddl-auto: update
#   hibernate:
#    naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
#   properties:
#    hibernate:
#     dialect: org.hibernate.dialect.MySQL5Dialect
#   database: mysql
#   show-sql: true
#  datasource:
#   driver-class-name: com.mysql.jdbc.Driver
#   url: jdbc:mysql://localhost:3306/testdb?verifyServerCertificate=false&useSSL=false&requireSSL=false
#   username: root
#   password: root
#   max-active: 50
#   max-idle: 5
#   min-idle: 5
#   initial-size: 10
#   testWhileIdle: false
#   validationQuery: SELECT 1
#   platform: MYSQL
#  http:
#   encoding:
#    charset: UTF-8


spring:
  profiles: tomMySQL
#  datasource:
#   driver-class-name: com.mysql.jdbc.Driver
#   url: jdbc:mysql://localhost:3306/testdb?verifyServerCertificate=false&useSSL=false&requireSSL=false
#   username: root
#   password: root
---


# ###########################################################
# H2 Database
# ###########################################################

spring:
     profiles: h2InMemoryDatabase
     h2:
      console:
       enabled: true
       path: /h2-console
     jpa:
      database-platform: H2
      hibernate:
       ddl-auto: create-drop
       naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
      database: h2
      show-sql: false
     datasource:
       driver-class-name: org.h2.Driver
       url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
       username: root
       password: root
       validation-query: select 1
     jooq:
       sql-dialect: org.hibernate.dialect.H2Dialect






